name: Lint
description: Check the code style
runs:
  using: composite
  steps:
    - name: Fmt
      shell: bash
      run: cargo fmt --check

    - name: Clippy
      shell: bash
      run: cargo clippy -- -D warnings
